spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/subway?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: zeratul1
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath*:schema.sql
    initialization-mode: always
handlebars:
  suffix: .html
  enabled: true
security:
  jwt:
    token:
      secret-key: my_secret_is_secret
      expire-length: 3600000