handlebars:
  suffix: .html
  enabled: true
security:
  jwt:
    token:
      secret-key: my_secret_is_secret
      expire-length: 3600000
springdoc:
  swagger-ui:
    path: /api-docs.html
    operations-sorter: alpha

spring:
  profiles:
    active: local