spring:
  config:
    activate:
      on-profile: remote
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mysql://192.168.0.239:8080/subway?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath*:schema.sql
    initialization-mode: never
handlebars:
  suffix: .html
  enabled: true
security:
  jwt:
    token:
      secret-key: my_secret_is_secret
      expire-length: 3600000