spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_subway?serverTimezone=UTC&characterEncoding=UTF-8
    username: ecsimsw
    password: root
    schema: classpath:schema.sql
    initialization-mode: always

handlebars:
  suffix: .html
  enabled: true
